name: Publish Release

on:
    workflow_dispatch:
    # repository_dispatch:
    #     types: [ stdlib-release-pipeline ]

jobs:
    publish-release:
        name: Release Package
        runs-on: ubuntu-latest
        if: github.repository_owner == 'ballerina-platform'
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Create lib directory if not exists
                run: mkdir -p ballerina/lib

            # -   name: Run Trivy vulnerability scanner
            #     uses: aquasecurity/trivy-action@master
            #     with:
            #         scan-type: 'rootfs'
            #         scan-ref: '/github/workspace/ballerina/lib'
            #         format: 'table'
            #         timeout: '10m0s'
            #         exit-code: '1'

            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@2201.5.0
              with:
                  args: test ./ballerina

            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@2201.5.0
              with:
                  args: pack ./ballerina

            # - name: Ballerina Push
            #   uses: ballerina-platform/ballerina-action/@2201.5.0
            #   with:
            #       args: push
            #   env:
            #       WORKING_DIR: ./ballerina
            #       BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
